{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "laravel-app.secretName" . }}
  labels:
    {{- include "laravel-app.labels" . | nindent 4 }}
type: Opaque
data:
  # Application key
  APP_KEY: {{ include "laravel-app.appKey" . | b64enc }}
  
  # Database password
  DB_PASSWORD: {{ include "laravel-app.databasePassword" . | b64enc }}
  
  # Redis password
  REDIS_PASSWORD: {{ include "laravel-app.redisPassword" . | b64enc }}
  
  # Mail password
  MAIL_PASSWORD: {{ .Values.env.MAIL_PASSWORD | b64enc }}
  
  # AWS/MinIO credentials
  AWS_ACCESS_KEY_ID: {{ include "laravel-app.minioAccessKey" . | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ include "laravel-app.minioSecretKey" . | b64enc }}
  
  {{- with .Values.secret.data }}
  {{- range $key, $value := . }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
  {{- end }}
{{- end }} 