# version: '3.8'  # Удалено как устаревшее

services:
  # PHP 8.4 development container
  php-dev:
    build:
      context: .
      dockerfile: docker/8.4/Dockerfile
      target: development
    container_name: laravel-php-dev
    volumes:
      - .:/var/www/html
      - ./docker/8.4/php-dev.ini:/usr/local/etc/php/conf.d/99-dev.ini
    working_dir: /var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    networks:
      - laravel-dev

  # Node.js 20 development container
  node-dev:
    image: node:20-alpine
    container_name: laravel-node-dev
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    working_dir: /app
    environment:
      - NODE_ENV=development
    networks:
      - laravel-dev

  # PostgreSQL for development
  postgres-dev:
    image: postgres:15-alpine
    container_name: laravel-postgres-dev
    environment:
      POSTGRES_DB: laravel_dev
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: laravel_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - laravel-dev

  # Redis for development
  redis-dev:
    image: redis:7-alpine
    container_name: laravel-redis-dev
    ports:
      - "6379:6379"
    networks:
      - laravel-dev

  # Mailpit for email testing
  mailpit-dev:
    image: axllent/mailpit:latest
    container_name: laravel-mailpit-dev
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - laravel-dev

  nginx-dev:
    build:
      context: .
      dockerfile: docker/8.4/Dockerfile
      target: nginx-dev
    container_name: laravel-nginx-dev
    depends_on:
      - php-dev
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    networks:
      - laravel-dev

volumes:
  postgres_data:
  node_modules:

networks:
  laravel-dev:
    driver: bridge 