apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-dev
  labels:
    app: laravel-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-dev
  template:
    metadata:
      labels:
        app: laravel-dev
    spec:
      containers:
      - name: php-fpm
        image: laravel-dev:latest
        imagePullPolicy: Never  # Используем локальный образ
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: app-code
          mountPath: /var/www/html
        - name: php-logs
          mountPath: /var/log
        env:
        - name: APP_ENV
          value: "local"
        - name: APP_DEBUG
          value: "true"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - php
            - /var/www/html/public/health.php
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - php
            - /var/www/html/public/health.php
          initialDelaySeconds: 5
          periodSeconds: 5

      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: app-code
          mountPath: /var/www/html
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx.conf
        - name: nginx-logs
          mountPath: /var/log/nginx
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health.php
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health.php
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5

      volumes:
      - name: app-code
        hostPath:
          path: ${PROJECT_PATH:-/home/user/example-app1}  # Динамический путь с fallback
          type: Directory
      - name: nginx-config
        configMap:
          name: nginx-dev-config
      - name: php-logs
        emptyDir: {}
      - name: nginx-logs
        emptyDir: {} 