apiVersion: v1
kind: Service
metadata:
  name: laravel-dev-service
  labels:
    app: laravel-dev
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080  # Порт для доступа снаружи кластера
    protocol: TCP
  selector:
    app: laravel-dev 