apiVersion: v2
name: laravel-app
description: A Helm chart for Laravel application with optional dependencies
type: application
version: 0.1.0
appVersion: "1.0.0"
home: https://github.com/your-org/laravel-app
sources:
  - https://github.com/your-org/laravel-app
maintainers:
  - name: Laravel Team
    email: team@example.com

keywords:
  - laravel
  - php
  - web
  - application

dependencies:
  - name: redis
    version: "~20.0.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
    tags:
      - database
  - name: postgresql
    version: "~16.0.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
    tags:
      - database
  - name: minio
    version: "~17.0.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: minio.enabled
    tags:
      - storage

annotations:
  category: WebApplications
  licenses: MIT 