# Default values for laravel-app
# This is a YAML-formatted file.

# Global settings
global:
  imageRegistry: ""
  imagePullSecrets: []
  storageClass: ""

# Laravel application configuration
app:
  name: laravel-app
  env: production
  debug: false
  key: "base64:iBywKf/ApF6tFuctRKqKQI+sC73oQrXRIGkPGeV2rVY="  # Laravel APP_KEY
  url: "http://laravel-app.local"
  timezone: "UTC"
  locale: "en"
  fallbackLocale: "en"

# Image configuration
image:
  registry: docker.io
  repository: your-org/laravel-app
  tag: "latest"
  pullPolicy: IfNotPresent
  pullSecrets: []
  # Nginx sidecar image
  nginx:
    repository: localhost:32000/laravel-nginx
    tag: working
    pullPolicy: IfNotPresent

# Deployment configuration
replicaCount: 1

# Pod configuration
podAnnotations: {}
podLabels: {}
podSecurityContext:
  fsGroup: 1000

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  allowPrivilegeEscalation: false

# Service configuration
service:
  type: ClusterIP
  port: 80
  targetPort: 8000
  annotations: {}

# Ingress configuration
ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    # cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: laravel-app.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: laravel-app-tls
  #    hosts:
  #      - laravel-app.local

# Resources configuration
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

# Horizontal Pod Autoscaler
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Node selection
nodeSelector: {}
tolerations: []
affinity: {}

# Liveness and readiness probes
livenessProbe:
  enabled: true
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1

readinessProbe:
  enabled: true
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3
  successThreshold: 1

# Startup probe
startupProbe:
  enabled: true
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 30
  successThreshold: 1

# Persistent Volume for storage
persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 8Gi
  annotations: {}
  # Path where Laravel storage will be mounted
  mountPath: /var/www/html/storage

# ConfigMap and Secret configuration
configMap:
  create: true
  data: {}

secret:
  create: true
  data: {}

# Environment ConfigMap for .env file
envConfigMap:
  create: true
  additionalEnv: {}
  # Example additional environment variables:
  # additionalEnv:
  #   BROADCAST_DRIVER: log
  #   CACHE_PREFIX: laravel_cache
  #   SESSION_LIFETIME: 120
  #   QUEUE_FAILED_DRIVER: database-uuids

# Environment variables
env:
  # Database configuration (when using internal chart)
  DB_CONNECTION: pgsql
  DB_HOST: "laravel-app-postgresql"
  DB_PORT: "5432"
  DB_DATABASE: laravel
  DB_USERNAME: laravel
  DB_PASSWORD: "laravel-password"
  
  # Redis configuration
  REDIS_HOST: "laravel-app-redis-master"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: "redis-password"
  REDIS_DB: "0"
  
  # Cache configuration
  CACHE_DRIVER: redis
  SESSION_DRIVER: redis
  QUEUE_CONNECTION: redis
  
  # Mail configuration
  MAIL_MAILER: smtp
  MAIL_HOST: ""  # Will use internal Mailpit if empty
  MAIL_PORT: "1025"
  MAIL_USERNAME: ""
  MAIL_PASSWORD: ""
  MAIL_ENCRYPTION: ""
  MAIL_FROM_ADDRESS: "hello@example.com"
  MAIL_FROM_NAME: "Laravel App"
  
  # Storage configuration
  FILESYSTEM_DISK: local
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_DEFAULT_REGION: us-east-1
  AWS_BUCKET: ""
  AWS_ENDPOINT: ""  # Will use internal MinIO if empty
  AWS_USE_PATH_STYLE_ENDPOINT: "true"

# Job configuration for migrations and other tasks
jobs:
  migrate:
    enabled: true
    restartPolicy: OnFailure
    backoffLimit: 3
    activeDeadlineSeconds: 300
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi

# ServiceAccount
serviceAccount:
  create: true
  annotations: {}
  name: ""

# Network Policy
networkPolicy:
  enabled: false
  policyTypes:
    - Ingress
    - Egress
  ingress: []
  egress: []

# =============================================================================
# Dependencies Configuration
# =============================================================================

# Redis configuration
redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: true
    password: "redis-password"
  master:
    persistence:
      enabled: true
      size: 8Gi
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi

# PostgreSQL configuration
postgresql:
  enabled: true
  auth:
    postgresPassword: "postgres-password"
    username: laravel
    password: "laravel-password"
    database: laravel
  primary:
    persistence:
      enabled: true
      size: 8Gi
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi

# MinIO configuration
minio:
  enabled: true
  auth:
    rootUser: minioadmin
    rootPassword: "minio-password"
  defaultBuckets: "laravel"
  persistence:
    enabled: true
    size: 10Gi
  resources:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

# Mailpit configuration (custom deployment)
mailpit:
  enabled: true
  image:
    registry: docker.io
    repository: axllent/mailpit
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    ports:
      smtp: 1025
      http: 8025
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  persistence:
    enabled: false
    size: 1Gi

# External services configuration (when dependencies are disabled)
externalServices:
  # External PostgreSQL
  postgresql:
    host: ""
    port: 5432
    database: laravel
    username: laravel
    password: ""
    existingSecret: ""
    existingSecretPasswordKey: ""
  
  # External Redis
  redis:
    host: ""
    port: 6379
    password: ""
    existingSecret: ""
    existingSecretPasswordKey: ""
  
  # External MinIO/S3
  s3:
    endpoint: ""
    region: us-east-1
    bucket: ""
    accessKey: ""
    secretKey: ""
    existingSecret: ""
    existingSecretAccessKeyKey: ""
    existingSecretSecretKeyKey: ""
  
  # External SMTP
  smtp:
    host: ""
    port: 587
    username: ""
    password: ""
    encryption: tls
    existingSecret: ""
    existingSecretPasswordKey: "" 