name: CD - Development

on:
  push:
    branches: [ develop ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'development'
        type: choice
        options:
        - development
        - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ghcr.io/${{ github.repository }}/laravel-app
          ghcr.io/${{ github.repository }}/laravel-nginx
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Laravel app image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/k8s/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          BUILDKIT_INLINE_CACHE=1

    - name: Build and push Nginx image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/k8s/nginx.Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository }}/laravel-nginx:${{ github.sha }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          BUILDKIT_INLINE_CACHE=1

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Setup Helm
      uses: azure/setup-helm@v3
      with:
        version: 'latest'

    - name: Configure kubectl
      run: |
        echo "${{ secrets.KUBE_CONFIG_DEV }}" | base64 -d > kubeconfig
        export KUBECONFIG=kubeconfig

    - name: Deploy to Kubernetes
      run: |
        export KUBECONFIG=kubeconfig
        
        # Get the correct image tag
        IMAGE_TAG="${{ github.sha }}"
        
        # Update image tags in values file
        sed -i "s|image: localhost:32000/laravel-app:.*|image: ghcr.io/${{ github.repository }}/laravel-app:$IMAGE_TAG|g" helm/laravel-app/values-dev.yaml
        sed -i "s|image: localhost:32000/laravel-nginx:.*|image: ghcr.io/${{ github.repository }}/laravel-nginx:$IMAGE_TAG|g" helm/laravel-app/values-dev.yaml
        
        # Deploy using Helm
        helm upgrade --install laravel-app helm/laravel-app \
          --namespace laravel-app-dev \
          --create-namespace \
          --values helm/laravel-app/values-dev.yaml \
          --set-string image.tag=$IMAGE_TAG \
          --set-string image.repository=ghcr.io/${{ github.repository }}/laravel-app \
          --set-string nginx.image.tag=$IMAGE_TAG \
          --set-string nginx.image.repository=ghcr.io/${{ github.repository }}/laravel-nginx \
          --wait \
          --timeout=10m

    - name: Wait for deployment
      run: |
        export KUBECONFIG=kubeconfig
        kubectl rollout status deployment/laravel-app -n laravel-app-dev --timeout=300s

    - name: Run health check
      run: |
        export KUBECONFIG=kubeconfig
        
        # Wait for service to be ready
        kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=laravel-app -n laravel-app-dev --timeout=300s
        
        # Port forward and test health endpoint
        kubectl port-forward -n laravel-app-dev svc/laravel-app 8080:80 &
        PF_PID=$!
        
        # Wait for port forward to be ready
        sleep 10
        
        # Test health endpoint
        for i in {1..30}; do
          if curl -f http://localhost:8080/health; then
            echo "Health check passed"
            break
          fi
          echo "Health check attempt $i failed, retrying..."
          sleep 5
        done
        
        # Cleanup port forward
        kill $PF_PID || true

    - name: Run smoke tests
      run: |
        export KUBECONFIG=kubeconfig
        
        # Test basic connectivity
        kubectl port-forward -n laravel-app-dev svc/laravel-app 8080:80 &
        PF_PID=$!
        sleep 5
        
        # Test main page
        curl -f http://localhost:8080/ || echo "Main page test failed"
        
        # Test Laravel routes
        curl -f http://localhost:8080/api/health || echo "API health test failed"
        
        kill $PF_PID || true

    - name: Notify deployment status
      if: always()
      run: |
        if [ "${{ job.status }}" == "success" ]; then
          echo "✅ Deployment to development successful!"
          echo "App URL: http://laravel-app.local/"
        else
          echo "❌ Deployment to development failed!"
          exit 1
        fi 